name: CI DevSecOps

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  semgrep-sast:
    name: SAST - Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

  dependency-check:
    name: SCA - OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "observability-app"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: reports

      - name: Fail on high severity vulnerabilities
        run: |
          if grep -qi "HIGH" reports/dependency-check-report.html; then
            echo "🚨 High severity vulnerabilities found. Failing pipeline."
            exit 1
          else
            echo "✅ No high severity vulnerabilities detected."
          fi
